MyPets/Controllers/PersonalCenterController.cs
using MyPets.DALFactory;
using MyPets.IDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyPets.Model;
using MyPets.BLL;
using System.Reflection;

namespace MyPets.Controllers
{
    public class PersonalCenterController : Controller
    {
        //
        // GET: /PersonalCenter/
        IBLL.IUserInfoServices UserInfo = new BLL.UserInfoServices();
        IBLL.IOrderDetailServices OrderDetail = new BLL.OrderDetailServices();
        IBLL.IOrderServices Order = new BLL.OrderServices();
        IBLL.IGoodsCommentServices GoodsCommentServices = new BLL.GoodsCommentServices();
        IDBSession db = new DBSession();
        public ActionResult Index(string user)
        {
            var userinfo = UserInfo.LoadEntities(u => u.UserName == user).FirstOrDefault();
            return View();
        }

        public ActionResult myorder()
        {
            MyPetsEntities db = new MyPetsEntities();
            IEnumerable<Order> model = from s in db.Order select s;
            //ViewBag.Order = model;
            return View(model);
        }
        public ActionResult Comment()
        {
            string name = Session["UserName"].ToString();
            var x = UserInfo.LoadEntities(g => g.UserName == name).FirstOrDefault();
            var Detail = OrderDetail.LoadEntities(g => g.UserId == x.UserId && g.OrderState==false).ToList();
            return View(Detail);
        }
        public ActionResult basicinformation()
        {
            BLL.UserInfoServices server = new BLL.UserInfoServices();
            string userName = Session["UserName"].ToString();
            var model = server.LoadEntities(o => o.UserName == userName).FirstOrDefault();
            return View(model);

        }
        public ActionResult goodsreview()
        {
            MyPetsEntities db = new MyPetsEntities();
            var mypet = db.Goods.Select(x => x);
            int goodid = mypet.FirstOrDefault().GoodsId;
            var myComment = db.GoodsComment.Select(x => x);
            ViewBag.Comment = myComment;
            ViewBag.MyPet = mypet;
            return View();
        }
        [HttpPost]
        public ActionResult goodsComment()
        {
            int id = int.Parse(Request["id"]);//获取前台隐藏标签的value值，即商品Id
            //var gc=GoodsCommentServices.LoadEntities(g=>g.C)
            //MyPetsEntities db = new MyPetsEntities();
            string name = Session["UserName"].ToString();//用户登录成功后，进行存储的用户名
            var x = UserInfo.LoadEntities(g => g.UserName == name).FirstOrDefault();
            GoodsCommentServices.AddEntity(new GoodsComment
            {
                CommentTime = System.DateTime.Now,
                CommentContent = Request["content"],
                GoodsId = id,
                UsersId = x.UserId,
                IsReply = true
            });

            //db.GoodsComment.Add(gc);
            db.SaveChanges();
            return Content("<script>alert('评论成功！');window.location.href='/PersonalCenter/goodsreview';</script>");

        }
        public ActionResult myshop()
        {
            return View();
        }
        public ActionResult privatenews()
        {
            return View();
        }
        //修改密码
        public ActionResult AlterUserPassword()
        {
            string userNameSession = Session["UserName"].ToString();
            string userPassword = Request["userPassword"];
            BLL.UserInfoServices userInfoService = new UserInfoServices();
            var model = userInfoService.LoadEntities(o => o.UserName == userNameSession).FirstOrDefault();
            model.UserPwd = userPassword;
            model.ConfirmPwd = userPassword;
            userInfoService.EditEntity(model);
            return Json("ok", JsonRequestBehavior.AllowGet);
        }
        //修改电话
        public ActionResult AlterUserPhone()
        {
            string userNameSession = Session["UserName"].ToString();
            string userPhone = Request["userPhone"];
            BLL.UserInfoServices userInfoService = new UserInfoServices();
            var model = userInfoService.LoadEntities(o => o.UserName == userNameSession).FirstOrDefault();
            model.UserPhone = userPhone;
            userInfoService.EditEntity(model);
            return Json("ok", JsonRequestBehavior.AllowGet);
        }
        //修改邮箱
        public ActionResult AlterUserEmail()
        {
            string userNameSession = Session["UserName"].ToString();
            string userEmail = Request["userEmail"];
            BLL.UserInfoServices userInfoService = new UserInfoServices();
            var model = userInfoService.LoadEntities(o => o.UserName == userNameSession).FirstOrDefault();
            model.UserEmail = userEmail;
            userInfoService.EditEntity(model);
            return Json("ok", JsonRequestBehavior.AllowGet);
        }
    }
}

MyPets/Views/PersonalCenter/Comment.cshtml
@{
    ViewBag.Title = "Comment";
    Layout = "~/Views/Shared/_LayoutPersonalCenter.cshtml";
}
@model IEnumerable<MyPets.Model.OrderDetail>

@section Comment{
    <link href="~/Content/Home/css/Comment.css" rel="stylesheet" />
}
<div class="main">
    <div class="top">
        <div class="goods">商品</div>
        <div class="name">名字</div>

        <div class="price">价格</div>
        <div class="num">订单号</div>
        <div class="time">时间</div>

        <div class="qupingjia ">操作</div>
    </div>
    @foreach (var g in Model)
    {
        <div class="mbody">
            <div class="goods"><img src="@Url.Content(g.Goods.GoodsImg1)" style="width: 100px; height: 100px" /></div>
            <div class="name">@Html.DisplayFor(a => g.Goods.GoodsName)</div>

            <div class="price">@Html.DisplayFor(a => g.Goods.GoodsPrice)</div>
            <div class="num">@Html.DisplayFor(a => g.OrderNumber)</div>
            <div class="time">@Html.DisplayFor(a => g.Order.OrderTime)</div>
            <div class="qupingjia ">
                <a href="@Url.Action("Comment","Home",new{ id=g.GoodsId,detailid=g.DetailId})"> 去评价</a>
            </div>
        </div>
    }
</div>

MyPets/Views/PersonalCenter/Index.cshtml
@model MyPets.Model.UserInfo
@{
    ViewBag.Title = "基本信息";
    Layout = "~/Views/Shared/_LayoutPersonalCenter.cshtml";
}
<br />
<div class="contact" style="margin-left:200px;">
    
     欢迎来到个人中心！
                

</div>

MyPets/Views/PersonalCenter/basicinformation.cshtml
@model MyPets.Model.UserInfo
@{
    ViewBag.Title = "basicinformation";
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>基本信息</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!--   Core JS Files   -->
    <script src="~/Content/PersonalCenter/js/jquery-1.10.2.js"></script>
    <script src="~/Content/PersonalCenter/js/bootstrap.min.js"></script>

    <!--  Checkbox, Radio & Switch Plugins -->
    <script src="~/Content/PersonalCenter/js/bootstrap-checkbox-radio-switch.js"></script>

    <!--  Charts Plugin -->
    <script src="~/Content/PersonalCenter/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="~/Content/PersonalCenter/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
    <script src="~/Content/PersonalCenter/js/light-bootstrap-dashboard.js"></script>

    <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
    <script src="~/Content/PersonalCenter/js/demo.js"></script>

    @*基本信息表单验证和上传头像*@
    <script src="~/Content/PersonalCenter/js/validateForm.js"></script>
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <!-- Bootstrap core CSS     -->
    <link href="~/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Animation library for notifications   -->
    <link href="~/Content/PersonalCenter/css/animate.min.css" rel="stylesheet" />

    <!--  Light Bootstrap Table core CSS    -->
    <link href="~/Content/PersonalCenter/css/light-bootstrap-dashboard.css" rel="stylesheet" />


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="~/Content/PersonalCenter/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="~/Content/PersonalCenter/css/pe-icon-7-stroke.css" rel="stylesheet" />
    <link herf="assets/css/basic.css" rel="stylesheet" />

    <script type="text/javascript">
        $(function () {
            AlterUserPassword();
            AlterUserPhone();
            AlterUserEmail();
        });

        //修改密码
        function AlterUserPassword() {
            $('#btnUserPassword').click(function () {
                var UserPassword = $('#txtUserPassword').val();
                $.post("/PersonalCenter/AlterUserPassword", { userPassword: UserPassword }, function (data) {
                    if (data == "ok") {
                        alert("修改成功");
                        history.go(0);
                    }
                });
            });
        }
        //修改电话号
        function AlterUserPhone() {
            $('#btnUserPhone').click(function () {
                var UserPhone = $('#txtUserPhone').val();
                $.post("/PersonalCenter/AlterUserPhone", { userPhone: UserPhone }, function (data) {
                    if (data == "ok") {
                        alert("修改成功");
                        history.go(0);
                    }
                });
            });
        }
        //修改邮箱
        function AlterUserEmail() {
            $('#btnUserEmail').click(function () {
                var UserEmail = $('#txtUserEmail').val();
                $.post("/PersonalCenter/AlterUserEmail", { userEmail: UserEmail }, function (data) {
                    if (data == "ok") {
                        alert("修改成功");
                        history.go(0);
                    }
                });
            });
        }
    </script>

    <style type="text/css">
        .contact *:focus {
            outline: none;
        }

        .contact {
            width: 700px;
            height: auto;
            background: #f6f6f6;
            margin: 40px auto;
            padding: 10px;
        }

            .contact ul {
                width: 650px;
                margin: 0 auto;
            }

                .contact ul li {
                    border-bottom: 1px solid #dfdfdf;
                    list-style: none;
                    padding: 30px;
                }

                    .contact ul li label {
                        width: 120px;
                        display: inline-block;
                        float: left;
                    }

                    .contact ul li input[type=text], .contact ul li input[type=password] {
                        width: 220px;
                        height: 25px;
                        border: 1px solid #aaa;
                        padding: 3px 8px;
                        border-radius: 5px;
                    }

                    .contact ul li input:focus {
                        border-color: #c00;
                    }

                    .contact ul li input[type=text] {
                        transition: padding .25s;
                        -o-transition: padding .25s;
                        -moz-transition: padding .25s;
                        -webkit-transition: padding .25s;
                    }

                    .contact ul li input[type=password] {
                        transition: padding .25s;
                        -o-transition: padding .25s;
                        -moz-transition: padding .25s;
                        -webkit-transition: padding .25s;
                    }

                    .contact ul li input:focus {
                        padding-right: 70px;
                    }

        .btn {
            position: margin-left;
            margin-left: 230px;
            margin-top: 70px;
            margin-right: 30px;
            margin-bottom: 20px;
        }

        .tips {
            color: rgba(0, 0, 0, 0.5);
            padding-left: 10px;
        }

        .tips_true, .tips_false {
            padding-left: 10px;
        }

        .tips_true {
            color: green;
        }

        .tips_false {
            color: red;
        }

        input[type="submit"], button[type=submit] {
            background: none repeat scroll 0 0 #5a88ca;
            border: medium none;
            color: #fff;
            padding: 4px 16px;
            text-transform: uppercase;
        }
    </style>
</head>
<body>

    <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="assets/img/sidebar-5.jpg">
            <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="PersonalCenter/Index" class="simple-text">
                        个人中心
                    </a>
                </div>

                <ul class="nav">

                    <li class="active">
                        <a href="@Url.Action("basicinformation",new {user=Session["UserName"] })">
                            <i class="pe-7s-user"></i>
                            <p>基本信息</p>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("myorder",new {user=Session["UserName"] })">
                            <i class="pe-7s-graph"></i>
                            <p>我的订单</p>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <i class="pe-7s-note2"></i>
                            <p>私信</p>
                        </a>
                    </li>
                    @*<li>
                            <a href="@Url.Action("Comment",new {user=Session["UserName"] })">
                                <i class="pe-7s-news-paper"></i>
                                <p>商品评论</p>
                            </a>
                        </li>*@
                    <li>
                        <a href="@Url.Action("goodsreview",new {user=Session["UserName"] })">
                            <i class="pe-7s-news-paper"></i>
                            <p>商品评论</p>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="pe-7s-science"></i>
                            <p>帖子管理</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Shop",new { user=Session["UserName"].ToString()})">
                            <i class="pe-7s-map-marker"></i>
                            <p>我的店铺</p>
                        </a>
                    </li>

                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">基本信息</a>
                    </div>
                    <div class="collapse navbar-collapse">
                    </div>
                </div>
            </nav>
            <div class="contact">
                <form name="form1" method="post">
                    <ul>
                        <li>
                            <label>姓名：@Html.DisplayFor(a => a.UserName)</label>

                            <input type="text" name="yourname" id="txtUserName" placeholder="请输入用户名" onblur="checkna()" required />
                            <input type="button" value="修改" id="btnUserName">
                            <span class="tips" id="divname">长度1~12个字符</span>

                        </li>
                        @*<li>
                                <label>性别：女</label>
                                <input type="submit" value="修改">
                                <input type="text" name="yoursex" placeholder="请输入性别" onblur="checksex()" required /><span class="tips" id="divsex"></span>
                            </li>*@
                        <li>
                            <label>密码：@Html.DisplayFor(a => a.UserPwd)</label>

                            <input type="password" name="yourpass" id="txtUserPassword" placeholder="请输入你的密码" onblur="checkpsd1()" required />
                            <input type="button" value="修改" id="btnUserPassword">
                            <span class="tips" id="divpassword1">密码由字母和数字组成</span>

                        </li>
                        <li>
                            <label>确认密码：@Html.DisplayFor(a => a.ConfirmPwd)</label>
                            <input type="password" name="yourpass2" placeholder="请再次输入你的密码" onblur="checkpsd2()" required />
                            <span class="tips" id="divpassword2">两次密码需要相同</span>
                        </li>
                        <li>
                            <label>手机号码：@Html.DisplayFor(a => a.UserPhone)<</label>
                            <input type="text" name="yourphone" id="txtUserPhone" placeholder="请输入手机号码" onblur="checktel()" required />
                            <input type="button" value="修改" id="btnUserPhone">
                            <span class="tips" id="divphonenumber">长度11个字符</span>
                        </li>
                        <li>
                            <label>邮箱：@Html.DisplayFor(a => a.UserEmail)</label>

                            <input type="text" name="youremail" id="txtUserEmail" placeholder="请输入你的邮箱" onblur="checkmail()" required />
                            <input type="button" id="btnUserEmail" value="修改">
                            <span class="tips" id="divmail">请输入正确的邮箱格式</span>

                        </li>
                    </ul>
                    <b class="btn">
                        <input type="submit" value="提交" />
                        <input type="reset" value="取消" />
                    </b>
                </form>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="#">
                                    首页
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    联系客服
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    联系我们
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    关于我们
                                </a>
                            </li>
                        </ul>
                    </nav>

                </div>
            </footer>
        </div>
    </div>
</body>
</html>

MyPets/Views/PersonalCenter/goodsreview.cshtml
@{
    ViewBag.Title = "goodsreview";
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>商品视图</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="~/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="~/Content/PersonalCenter/css/animate.min.css" rel="stylesheet" />

    <!--  Light Bootstrap Table core CSS    -->
    <link href="~/Content/PersonalCenter/css/light-bootstrap-dashboard.css" rel="stylesheet" />


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="~/Content/PersonalCenter/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>

    <link href="~/Content/PersonalCenter/css/pe-icon-7-stroke.css" rel="stylesheet" />
    <style type="text/css">
        table.shop_table {
            border-bottom: 1px solid #ddd;
            border-right: 1px solid #ddd;
            margin-bottom: 50px;
            width: 100%;
        }

        thead {
            display: table-header-group;
            vertical-align: middle;
            border-color: inherit;
        }

        tr {
            display: table-row;
            vertical-align: inherit;
            border-color: inherit;
        }

        table.shop_table th, table.shop_table td {
            border-left: 1px solid #ddd;
            border-top: 1px solid #ddd;
            padding: 15px;
            text-align: center;
        }

        tbody {
            display: table-row-group;
            vertical-align: middle;
            border-color: inherit;
        }

        tr {
            display: table-row;
            vertical-align: inherit;
            border-color: inherit;
        }

        td.actions div.coupon {
            float: left;
        }

        input[type="text"], input[type="password"], input[type="email"], textarea {
            border: 1px solid #ddd;
            padding: 10px;
        }

        input[type="submit"], button[type=submit] {
            background: none repeat scroll 0 0 #5a88ca;
            border: medium none;
            color: #fff;
            padding: 11px 20px;
            text-transform: uppercase;
        }

        input[type="submit"], button[type=submit] {
            background: none repeat scroll 0 0 #5a88ca;
            border: medium none;
            color: #fff;
            padding: 11px 20px;
            text-transform: uppercase;
        }

        input[type="submit"], button[type=submit] {
            background: none repeat scroll 0 0 #5a88ca;
            border: medium none;
            color: #fff;
            padding: 11px 20px;
            text-transform: uppercase;
        }
    </style>
</head>
<body>

    <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="assets/img/sidebar-5.jpg">

            <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="PersonalCenter/Index" class="simple-text">
                        个人中心
                    </a>
                </div>

                <ul class="nav">
                    <li>
                        <a href="@Url.Action("basicinformation",new {user=Session["UserName"] })">
                            <i class="pe-7s-user"></i>
                            <p>基本信息</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("myorder",new {user=Session["UserName"] })">
                            <i class="pe-7s-graph"></i>
                            <p>我的订单</p>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <i class="pe-7s-note2"></i>
                            <p>私信</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Comment",new {user=Session["UserName"] })">
                            <i class="pe-7s-news-paper"></i>
                            <p>商品评论</p>
                        </a>
                    </li>
                    <li class="active">
                        <a href="@Url.Action("goodsreview",new {user=Session["UserName"] })">
                            <i class="pe-7s-news-paper"></i>
                            <p>追加评论</p>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="pe-7s-science"></i>
                            <p>帖子管理</p>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Shop",new { user=Session["UserName"].ToString()})">
                            <i class="pe-7s-map-marker"></i>
                            <p>我的店铺</p>
                        </a>
                    </li>

                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">商品评论</a>
                    </div>
                    <div class="collapse navbar-collapse">


                    </div>
                </div>
            </nav>


            <div class="content">


                <table cellspacing="0" class="shop_table cart">
                    <thead>
                        <tr>
                            <th class="product-remove">&nbsp;</th>
                            <th class="product-thumbnail">&nbsp;</th>
                            <th class="product-name">商品</th>
                            <th class="product-price">价格</th>
                            <th class="product-quantity">评价</th>
                            <th class="product-subtotal">追加评价</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.MyPet)
                        {
                            <tr class="cart_item">
                                <td class="product-remove">
                                    <a title="Remove this item" class="remove" href="#"></a>
                                </td>
                                <td class="product-thumbnail">
                                    <a href="single-product.html"><img width="145" height="145" alt="poster_1_up" class="shop_thumbnail" src="@Url.Content(item.GoodsImg1)"></a>
                                </td>
                                <td class="product-name">
                                    <a href="single-product.html">@item.GoodsName</a>
                                </td>
                                <td class="product-price">
                                    <span class="amount">@item.GoodsPrice</span>
                                </td>
                                <td class="product-appraise">
                                    <div class="quantity buttons_added">
                                        @foreach (var item1 in ViewBag.Comment)
                                        {
                                            if (item.GoodsId == item1.GoodsId)
                                            {
                                                <span class="amount">@item1.CommentContent</span>
                                            }
                                        }
                                    </div>
                                </td>
                                <td class="product-advice">
                                    @using (Html.BeginForm("goodsComment", "PersonalCenter", FormMethod.Post, new { id = "MyFrom" }))
                                    {<span class="amount">
                                        <input type="hidden" value="@item.GoodsId" name="id" />
                                        <input type="text" placeholder="追加评价..." value="" name="content" />
                                    </span>
                                    <input type="submit" value="评论" />
                                    }

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="#">
                                    首页
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    联系客服
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    联系我们
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    关于我们
                                </a>
                            </li>
                        </ul>
                    </nav>

                </div>
            </footer>


        </div>
    </div>


</body>

<!--   Core JS Files   -->
<script src="~/Content/PersonalCenter/js/jquery-1.10.2.js"></script>
<script src="~/Content/PersonalCenter/js/bootstrap.min.js"></script>

<!--  Checkbox, Radio & Switch Plugins -->
<script src="~/Content/PersonalCenter/js/bootstrap-checkbox-radio-switch.js"></script>

<!--  Charts Plugin -->
<script src="~/Content/PersonalCenter/js/chartist.min.js"></script>

<!--  Notifications Plugin    -->
<script src="~/Content/PersonalCenter/js/bootstrap-notify.js"></script>

<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

<!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<script src="~/Content/PersonalCenter/js/light-bootstrap-dashboard.js"></script>

<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
<script src="~/Content/PersonalCenter/js/demo.js"></script>

</html>