MyPets/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using MyPets.IDAL;
using MyPets.DALFactory;

namespace MyPets.Controllers
{
    public class StoreController : Controller
    {
        // GET: Store
        IBLL.IShopServices ShopServices = new BLL.ShopServices();
        IBLL.IGoodsServices GoodsService = new BLL.GoodsServices();
        IBLL.ICollectServices CollectService = new BLL.CollectServices();
        IBLL.IUserInfoServices UserInfoServices = new BLL.UserInfoServices();
        IBLL.IShopCartServices ShopCartServices = new BLL.ShopCartServices();
        IDBSession db = new DBSession();
        public ActionResult Index(int? shopid)
        {
            int id = (shopid ?? 1);
            var discountgoods = GoodsService.LoadEntities(g => g.IsDiscount == true && g.ShopId == id).ToList();
            ViewData["discountgoods"] = discountgoods; //促销商品
            var shop = ShopServices.LoadEntities(s => s.ShopId == id).FirstOrDefault();
            ViewBag.Title = shop.ShopName;           
            Session["shopid"] = id;
            Session["hascollect"] = "no";  //判断是否收藏
            if (Session["UserName"] != null)
            {
                var name = Session["UserName"].ToString();
                var user = UserInfoServices.LoadEntities(u => u.UserName == name).FirstOrDefault();
                var collect = CollectService.LoadEntities(c => c.UserId == user.UserId).FirstOrDefault();
                if (collect == null)
                {
                    Session["hascollect"] = "no";
                }
                else Session["hascollect"] = "yes";
            }
            return View();
        }
        public ActionResult PartialAllGoods(int? page)//全部
        {
            int id = Convert.ToInt32(Session["shopid"]);
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            var allgoods = GoodsService.LoadEntities(g => g.ShopId == id).ToList();
            ViewData["allgoods"] = allgoods;
            if (Request.IsAjaxRequest())
            {
                return PartialView("PartialAllGoods", allgoods.ToPagedList(pageNumber, pageSize));
            }
            else return View("PartialAllGoods", allgoods.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult PartialDogGoods(int? page)//狗
        {
            int id = Convert.ToInt32(Session["shopid"]);
            var doggoods = GoodsService.LoadEntities(g => g.ShopId == id && g.SeriesName == "狗狗商品").ToList();
            ViewData["doggoods"] = doggoods;
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            if (Request.IsAjaxRequest())
            {
                return PartialView("PartialDogGoods", doggoods.ToPagedList(pageNumber, pageSize));
            }
            else return View("PartialDogGoods", doggoods.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult PartialCatGoods(int? page)//猫
        {
            int id = Convert.ToInt32(Session["shopid"]);
            var catgoods = GoodsService.LoadEntities(g => g.ShopId == id && g.SeriesName == "猫猫商品").ToList();
            ViewData["doggoods"] = catgoods;
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            if (Request.IsAjaxRequest())
            {
                return PartialView("PartialCatGoods", catgoods.ToPagedList(pageNumber, pageSize));
            }
            else return View("PartialCatGoods", catgoods.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult PartialLittleGoods(int? page)//小宠物
        {
            int id = Convert.ToInt32(Session["shopid"]);
            var littlegoods = GoodsService.LoadEntities(g => g.ShopId == id && (g.SeriesName == "奇趣小宠" || g.SeriesName == "爬虫用品")).ToList();
            ViewData["doggoods"] = littlegoods;
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            if (Request.IsAjaxRequest())
            {
                return PartialView("PartialLittleGoods", littlegoods.ToPagedList(pageNumber, pageSize));
            }
            else return View("PartialLittleGoods", littlegoods.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult PartialWaterGoods(int? page)//水族
        {
            int id = Convert.ToInt32(Session["shopid"]);
            var watergoods = GoodsService.LoadEntities(g => g.ShopId == id && g.SeriesName == "水族市场").ToList();
            ViewData["doggoods"] = watergoods;
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            if (Request.IsAjaxRequest())
            {
                return PartialView("PartialWaterGoods", watergoods.ToPagedList(pageNumber, pageSize));
            }
            else return View("PartialWaterGoods", watergoods.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult GoodsDetail(int goodsid)
        {
            int id = Convert.ToInt32(Session["shopid"]);
            var shopname = ShopServices.LoadEntities(s => s.ShopId == 1).FirstOrDefault();
            ViewBag.Title = shopname.ShopName;
            var discountgoods = GoodsService.LoadEntities(g => g.IsDiscount == true && g.ShopId == id).OrderBy(g => Guid.NewGuid()).Take(4).ToList();
            ViewData["discountgoods"] = discountgoods; //促销商品
            var goods = GoodsService.LoadEntities(g => g.GoodsId == goodsid).FirstOrDefault();
            var relatedgoods = GoodsService.LoadEntities(g => g.GoodsId == 1 && g.DetailName == goods.DetailName).ToList();
            ViewData["relatedgoods"] = relatedgoods;
            return View(goods);
        }
        public ActionResult CollectStore() //收藏店铺
        {
            if (Session["UserName"] == null)
            {
                return Content("<script>alert('登录后才能收藏店铺哦！');history.go(-1);</script>");
            }
            else
            {
                var id = Convert.ToInt32(Session["shopid"]);
                var name = Session["UserName"].ToString();
                var userid = UserInfoServices.LoadEntities(u => u.UserName == name).FirstOrDefault();
                CollectService.AddEntity(new Model.Collect
                {
                    ShopId = Convert.ToInt32(Session["shopid"]),
                    UserId = userid.UserId
                });
                db.SaveChanges();
                return Content("<script>alert('收藏成功！');window.location.href='/Store/Index'</script>");
            }
        }
        public ActionResult CancleCollect() //取消收藏
        {
            var name = Session["UserName"].ToString();
            var user = UserInfoServices.LoadEntities(u => u.UserName == name).FirstOrDefault();
            var del = CollectService.LoadEntities(c => c.UserId == user.UserId).FirstOrDefault();
            CollectService.DeleteEntity(del);
            Session["hascollect"] = "no";
            return RedirectToAction("Index");
        }
        public ActionResult SearchShopGoods(string searchthing, int? page) //店内搜索
        {
            if (searchthing != "")
            {
                var id = Convert.ToInt32(Session["shopid"]);
                var goods = GoodsService.LoadEntities(g => g.ShopId == id && g.GoodsName.Contains(searchthing)).ToList();
                int pageSize = 15;
                int pageNumber = (page ?? 1);
                ViewBag.goods = searchthing;
                return View(goods.ToPagedList(pageNumber, pageSize));
            }
            else return Content("<script>alert('搜索不能为空！');history.go(-1);</script>");
        }
        public ActionResult PartialCart()
        {
            var name = Session["UserName"].ToString();
            int countsum = 0;
            var cart = ShopCartServices.LoadEntities(s => s.UserName == name).ToList();
            ViewBag.sum = cart.Count(); //统计购物车数量
            for (int i = 0; i < cart.Count(); i++)
            {
                int a = cart[i].GoodsId;
                var goods = GoodsService.LoadEntities(g => g.GoodsId == a).FirstOrDefault();
                if (goods.IsDiscount)
                {
                    countsum = countsum + cart[i].GoodsSum * Convert.ToInt32(goods.DiscountPrice);
                }
                else countsum = countsum + cart[i].GoodsSum * Convert.ToInt32(goods.GoodsPrice);

            }
            ViewBag.count = countsum;
            return PartialView();
        }
        public ActionResult LoginOff()
        {
            Session["UserName"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

MyPets/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<script src="~/ckeditor/ckeditor.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
@*<script src="~/ckfinder/ckfinder.js"></script>
<script src="~/ckfinder/config.js"></script>*@
<script type="text/javascript">
    $(function () {
        CKEDITOR.replace('content');
    });
</script>
<style>

</style>
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>
<div>
    <textarea id="content" name="content"></textarea>
</div>

MyPets/Views/Home/Comment.cshtml
@{
    ViewBag.Title = "Comment";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
@model MyPets.Model.Goods
@section jiesuan{
    <link href="~/Content/Home/css/GoodsComment.css" rel="stylesheet" />
}
@using (Html.BeginForm("AddToGoodsComment", "Home", FormMethod.Post))
{
    <div class="pingjia">
        <div id="pingjia1">商品评价</div>
        <div style="height:60px;border-bottom :1px solid #808080;border-top :1px solid #808080;">
            <div class="pingjia3">
                <div style="float:left;">评价满意度:</div>
                <select class="form-control" id="InputType" name="InputType" style="width:130px; margin-left:100px;">
                    <option>好评</option>
                    <option>中评</option>
                    <option>差评</option>
                </select>
            </div>
        </div>
        @Html.Hidden("id", Model.GoodsId)
        <div style="height:230px;">
            <div class="pingjia4">
                <div><img src="@Url.Content(Model.GoodsImg1)" style="height:150px;width:150px;" /></div>
                <div>@Html.DisplayFor(a => Model.GoodsName)</div>
            </div>
            <div class="pingjia5">
                <div style="float:right;">@DateTime.Now</div>
                <div class="neirong">
                    <input style="width:800px;height:160px;" id="Text1" type="text" name="content" placeholder="你的评价是对我们的肯定！" />
                </div>
            </div>
        </div>
        <div style="margin-left:400px;">
            <input type="submit" value="提交" id="sbt" style="width:100px;height:30px;" />
        </div>
    </div>
}

MyPets/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyPets/Views/Home/SearchShop.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<MyPets.Model.Shop>

@{
    ViewBag.Title = "searchShop";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
@section jiesuan{<link href="~/Content/Home/css/searchShop.css" rel="stylesheet" />}

<div id="Container">
    <p style="margin-top:10px;">找到相关店铺(<span style="color:RGB(255,101,0);">@ViewBag.num</span>)家</p>
    @foreach (@*MyPets.Model.Shop a in ViewData["searchShops"] as List<MyPets.Model.Shop>*@ var a in Model)
    {
        <div class="shopModel">
            <div class="shopMsg">
                <input type="hidden" name="shopId" /> 
                <div ><img src="@Url.Content(a.ShopImg)" /></div>             
                <div class="shopName"><a href="@Url.Action("Index","Store",new { shopid=a.ShopId })">店铺：@Html.DisplayFor(n => a.ShopName)</a></div>                
                <div class="shopOwner">店长：@a.UserInfo.UserName</div>
            </div>
            <div class="shopGoods">
                @foreach (MyPets.Model.Goods b in a.Goods.Where(item => item.ShopId == @a.ShopId).Take(4).ToList())
                {
                    <img src="@Url.Content(b.GoodsImg1)" />
                }
            </div>
            <div class="toShop"><a href="@Url.Action("Index","Store",new { shopid=a.ShopId })">进入店铺>></a></div>
        </div>
    }
    <div style="margin:0 auto;width:300px;text-align:center;"> @Html.PagedListPager(Model, page => Url.Action("SearchShop", "Home", new { page, searchInput = @ViewData["searchInput"] }), new PagedListRenderOptions { LinkToFirstPageFormat = "首页", LinkToPreviousPageFormat = "上一页", LinkToNextPageFormat = "下一页", LinkToLastPageFormat = "尾页", MaximumPageNumbersToDisplay = 3 })</div>
</div>

MyPets/Views/Home/Shangpin.cshtml
@{
    ViewBag.Title = "Shangpin";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
@using PagedList
@using PagedList.Mvc
@*@model PagedList.IPagedList<MyPets.Model.Goods>*@
@model IEnumerable<MyPets.Model.Goods>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Content/Home/js/goods.js"></script>
    <link href="~/Content/Home/css/shangpin.css" rel="stylesheet" />
</head>
<body>
    <form id="form1">
        <div style="width:1200px;margin:0 auto;">
            <div class="top">
                @if (Session["sptype"].ToString() == "狗")
                {
                    <div class="leibie">
                        <div class="typeImgContainer">
                            <!--放小图片用的div-->
                        </div>
                        <div style="margin-left:50px;font-size:20px;">狗狗商品</div>
                    </div>
                    <div style="width:700px;float:left;">
                        <div style="margin-top:30px;">
                            <div class="lei">
                                <div>狗粮</div>
                                <div>狗罐头</div>
                                <div>狗零食</div>
                                <div>医疗保健</div>
                                <div>沐浴露</div>
                                <div>日用品</div>
                                <div>玩具</div>
                                <div>衣服</div>
                            </div>
                            <div>
                                <div class="one">
                                    <a href="@Url.Action("shangpin","Home",new { keyword="离乳期狗粮",type="狗"})" class="ones">离乳期犬粮</a>
                                    <a href="@Url.Action("shangpin","Home",new { keyword="幼犬粮",type="狗"})">幼犬粮</a>
                                    <a href="@Url.Action("shangpin","Home",new { keyword="成犬粮",type="狗"})">成犬粮</a>
                                    <a href="@Url.Action("shangpin","Home",new { keyword="老犬粮",type="狗"})">老犬粮</a>
                                    <a href="@Url.Action("shangpin","Home",new { keyword="全犬粮",type="狗"})">全犬粮</a>
                                </div>
                                <div class="one">
                                    <a href="" class="ones">成犬</a>
                                    <a href=""> 幼犬</a>
                                    <a href="">全犬粮</a>
                                </div>
                                <div class="one">
                                    <a href="" class="ones">  肉质零食</a>
                                    <a href="">咬骨咬胶</a>
                                    <a href="">奶制零食</a>
                                    <a href="">饼干素食</a>

                                </div>
                                <div class="one">
                                    <a href="" class="ones"> 美毛护肤</a>
                                    <a href="">补钙强骨</a>
                                    <a href="">微量矿物</a>
                                    <a href="">调理肠胃</a>
                                    <a href=""> 综合营养</a>

                                </div>
                                <div class="one">
                                    <a href="" class="ones">体内驱虫</a>
                                    <a href="">体外驱虫</a>
                                    <a href="">口腔修护</a>
                                    <a href="">眼部护理</a>
                                    <a href="">耳道清洁</a>
                                    <a href="">皮肤问题</a>
                                </div>
                                <div class="one">
                                    <a href="" class="ones">药用香波</a>
                                    <a href="">美毛去味</a>
                                    <a href="">特色毛发</a>
                                    <a href="">干洗粉</a>
                                    <a href="">洗手液</a>
                                </div>
                                <div class="one">
                                    <a href="" class="ones"> 休闲玩具</a>
                                    <a href=""> 互动玩具</a>
                                    <a href="">益智训导</a>
                                    <a href="">磨牙玩具</a>
                                    <a href="">洗澡用品</a>

                                </div>
                                <div class="one">
                                    <a href="" class="ones">宠物服装</a>
                                    <a href="">犬窝/犬笼</a>
                                    <a href="">毛毯/垫子凉席</a>
                                    <a href="">鞋子/袜子/帽子</a>

                                </div>
                            </div>
                        </div>
                    </div>
                }
                else if (Session["sptype"].ToString() == "猫")
                {
                    <div class="leibie">
                        <div class="typeImgContainer" style="background-position: -58px 0">
                            <!--放小图片用的div-->
                        </div>
                        <div style="margin-left:50px;font-size:20px;">猫猫商品</div>
                    </div>
                    <div style="width:700px;float:left;">
                        <div style="margin-top:30px;">
                            <div class="lei">
                                <div>宠物猫粮</div>
                                <div>猫罐头</div>
                                <div>猫猫零食</div>
                                <div>猫猫医疗</div>
                                <div>猫猫保健品</div>
                                <div>猫猫香波</div>
                                <div>日常用品</div>
                                <div>猫猫玩具</div>
                            </div>
                            <div>
                                <div class="one">
                                    <a href="@Url.Action("shangpin","Home",new { keyword="成猫粮",type="猫"})" class="ones">成猫粮</a>
                                    <a href="@Url.Action("shangpin","Home",new { keyword="幼猫湿粮",type="猫"})">幼猫粮</a>
                                    <a href="@Url.Action("shangpin","Home",new { keyword="成猫粮",type="猫"})">全猫粮</a>
                                    <a href="@Url.Action("shangpin","Home",new { keyword="幼猫湿粮",type="猫"})">老犬粮</a>
                                    <a href="@Url.Action("shangpin","Home",new { keyword="成猫粮",type="猫"})">老猫粮</a>
                                </div>
                                <div class="one">
                                    <a href="" class="ones">成猫湿粮</a>
                                    <a href=""> 幼猫湿粮</a>

                                </div>
                                <div class="one">
                                    <a href="" class="ones">  肉质零食</a>
                                    <a href="">猫条/猫草</a>
                                    <a href="">果冻</a>
                                    <a href="">猫咪洁牙零食</a>

                                </div>
                                <div class="one">
                                    <a href="" class="ones">体内驱虫</a>
                                    <a href="">体外驱虫</a>
                                    <a href="">口腔修护</a>
                                    <a href="">眼部护理</a>
                                    <a href="">耳道清洁</a>
                                    <a href="">皮肤问题</a>
                                </div>
                                <div class="one">
                                    <a href="" class="ones"> 美毛护肤</a>
                                    <a href="">补钙强骨</a>
                                    <a href="">微量矿物</a>
                                    <a href="">调理肠胃</a>
                                    <a href=""> 综合营养</a>
                                </div>
                                <div class="one">
                                    <a href="" class="ones">药用香波</a>
                                    <a href="">美毛去味</a>
                                    <a href="">特色毛发</a>
                                    <a href="">干洗粉</a>
                                    <a href="">洗手液</a>
                                </div>
                                <div class="one">
                                    <a href="" class="ones"> 休闲玩具</a>
                                    <a href=""> 互动玩具</a>
                                    <a href="">益智训导</a>
                                    <a href="">磨牙玩具</a>
                                    <a href="">洗澡用品</a>

                                </div>
                                <div class="one">
                                    <a href="" class="ones">猫窝猫笼</a>
                                    <a href="">毛毯/垫子</a>
                                    <a href="">精美饰品</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="right">
                @foreach (var g in Model)
                {
                    <div class="product">
                        <div class="tupian">
                            <a href="@Url.Action("goumai",new { id=g.GoodsId})">
                                <img src="@Url.Content(g.GoodsImg1)" style="width: 150px; height: 170px" />
                            </a>
                        </div>
                        <div class="jiage"><span style="color:red;font-size:20px;">￥@Html.DisplayFor(a => g.GoodsPrice)</span></div>
                        <div class="name">
                            <a href="">@Html.DisplayFor(a => g.GoodsName)</a>
                        </div>
                        <div style="height: 15px">
                            <div class="yishou">已售：@Html.DisplayFor(s => g.SellNum)</div>
                            <div class="pingjia">已有：<a href="">@Html.DisplayFor(s => g.SellNum)</a>人评价</div>
                        </div>
                        <div class="gouwu">
                            <a href="@Url.Action("AddToCart",new { id=@g.GoodsId})">
                                <input type="button" value="加入购物车" class="goumai" />
                            </a>
                        </div>
                    </div>
                }
                @*<div style="text-align:center;"> @Html.PagedListPager(Model, page => Url.Action("GetType", "goods", new { page, txttype = @ViewData["type"] }))</div>*@
            </div>

        </div>
    </form>
</body>
</html>

MyPets/Views/Home/buynow.cshtml
@model MyPets.Model.Goods
@{
    ViewBag.Title = "Buynow";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <script src="~/Content/Home/js/jquery.1.4.2-min.js"></script>
    <script src="~/Content/Home/js/payfor.js"></script>
    <style type="text/css">
        .add_chose a {
            float: left;
            margin: 5px 0 0 0;
            display: block;
            width: 15px;
            height: 15px;
            line-height: 99em;
        }

        .add_chose .text {
            float: left;
            margin: 0 5px;
            display: inline;
            border: solid 1px #ccc;
            padding: 4px 3px 4px 8px;
            width: 40px;
            line-height: 18px;
            font-size: 14px;
            color: #990000;
            font-weight: 800;
        }
    </style>
</head>
<body>
    <div style="position:absolute;left:250px;margin-top:50px;">
        <div style="border:solid 1px ;height:160px;">
            <div style="line-height:150px;float:left;width:350px;margin-left:20px;">
                <div style="line-height:50px;height:50px;">
                    商品名
                </div>
                <div>
                    @Html.DisplayFor(a => Model.GoodsName)
                </div>
            </div>
            <div style="line-height:150px;float:left;width:150px;">
                <div style="line-height:50px;height:50px;">
                    数量
                </div>
                1
                @*<div class="f_l add_chose">
                        <a class="reduce" onClick="setAmount.reduce('#qty_item_1')" href="javascript:void(0)"> - </a>
                        <input type="text" name="qty_item_1" value="1" id="qty_item_1" onKeyUp="setAmount.modify('#qty_item_1')" class="text" />
                        <a class="add" onClick="setAmount.add('#qty_item_1')" href="javascript:void(0)"> +</a>
                    </div>*@
            </div>
            <div style="line-height:150px;float:left;width:150px;">
                <div style="line-height:50px;height:50px;">
                    价格
                </div>
                <div>
                    @Html.DisplayFor(a => Model.GoodsPrice)
                </div>
            </div>
            <div style="line-height:150px;float:left;width:150px;">
                <div style="line-height:50px;height:50px;">
                    总价
                </div>
                <div class="list_sum">
                    <p class="sum_price">@Html.DisplayFor(a => Model.GoodsPrice)</p>
                </div>
            </div>
        </div>
@using (Html.BeginForm("AddBuy", "Home", FormMethod.Post))
{
    @Html.Hidden("id", Model.GoodsId)
        <div>
            <div style="border-color:red ;width:500px;border:solid 2px red ;margin-top:10px;float:left">
                <div style="height:50px;line-height:50px;margin-left:10px">
                    实付款：   ￥@Html.DisplayFor(a => Model.GoodsPrice)
                </div>
                <div style="height:50px;line-height:50px;margin-left:10px">
                    <input style="width:400px;height:50px;" id="Text1" type="text" name="content" placeholder="请填写地址！" />
                </div>
                <div style="height:50px;line-height:50px;margin-left:10px">
                    收货人：@Session["UserName"]
                    电话：@ViewData["Tel"]
                </div>
            </div>
            <div style="margin-left:550px;margin-top:50px;position:absolute;">
                @*<a href="@Url.Action("AddBuy","Home",new { id=Model.GoodsId})">
                    <input type="button" value="加入购物车" class="goumai" />
                </a>*@
                @*<a href="@Url.Action("AddBuy","Home",new { id=Model.GoodsId})">付款</a>*@

                <input type="submit" value="付款" id="sbt" style="width:100px;height:30px;" />
            </div>
        </div>
}
    </div>

</body>
</html>

MyPets/Views/Home/searchGoods.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<MyPets.Model.Goods>
@{
    ViewBag.Title = "searchGoods";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

@section jiesuan{<link href="~/Content/Home/css/searchGoods.css" rel="stylesheet" />}


<div id="Container">
    <p style="margin-top:10px;">找到相关商品(<span style="color:RGB(255,101,0);">@ViewBag.num</span>)件</p>
    @foreach (var g in Model)
    {
        <div class="product">
            <div class="tupian">
                <a href="@Url.Action("goumai",new { id=g.GoodsId})">
                    <img src="@Url.Content(g.GoodsImg1)" style="width: 150px; height: 170px" />
                </a>
            </div>
            <div class="jiage"><span style="color:red;font-size:20px;">￥@Html.DisplayFor(a => g.GoodsPrice)</span></div>
            <div class="name">
                <a href="">@Html.DisplayFor(a => g.GoodsName)</a>
            </div>
            <div style="height: 15px">
                <div class="yishou">已售：@Html.DisplayFor(s => g.SellNum)</div>
                <div class="pingjia">已有：<a href="">@Html.DisplayFor(s => g.SellNum)</a>人评价</div>
            </div>
            <div class="gouwu">
                <a href="@Url.Action("AddToCart",new { id=@g.GoodsId})">
                    <input type="button" value="加入购物车" class="goumai" />
                </a>
            </div>
        </div>
    }
    <div style="text-align:center;"> @Html.PagedListPager(Model, page => Url.Action("SearchGoods", "Home", new { page, searchInput = @ViewData["searchInput"] }), new PagedListRenderOptions { LinkToFirstPageFormat = "首页", LinkToPreviousPageFormat = "上一页", LinkToNextPageFormat = "下一页", LinkToLastPageFormat = "尾页", MaximumPageNumbersToDisplay = 5 })</div>
</div>

MyPets/Views/Home/zhifu.cshtml
@model MyPets.Model.Order
@{
    ViewBag.Title = "zhifu";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<div style="position:absolute;left:450px;margin-top:30px;border:solid 1px ;width:290px;">
    <div style="margin-left:20px;margin-top:13px">

        <img src="~/Content/Admin/images/tick-button-image.jpg " style="width:250px;height:250px;" />
    </div>
    <div style="margin-left:20px;height:50px;line-height:50px;">
        <span style="font-size:larger;color:#00ffff;"> 恭喜！购买成功</span>
    </div>
    <div style="margin-left:20px;height:50px;line-height:50px;">
        订单金额：@Model.OrderCount
    </div>
    <div style="margin-left:20px;height:50px;line-height:50px;">
        订单号：@Model.OrderNumber
    </div>
</div>