MyPets/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyPets.Models;
using MyPets.Model;
using MyPets.IDAL;
using PagedList;
using MyPets.DALFactory;
using MyPets.DAL;

namespace MyPets.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        IBLL.IUserInfoServices UserInfoServices = new BLL.UserInfoServices();
        IBLL.IGoodsServices GoodsServices = new BLL.GoodsServices();
        IBLL.IGoodsCommentServices GoodsCommentServices = new BLL.GoodsCommentServices();
        IBLL.IShopServices ShopServices = new BLL.ShopServices();
        IBLL.IBaikeServices BaikeServices = new BLL.BaikeServices();
        IBLL.ICollectServices CollectServices = new BLL.CollectServices();
        IBLL.IBaikeAnswerServices BaikeAnswerServices = new BLL.BaikeAnswerServices();
        IBLL.IBaikeQuestionServices BaikeQuestionServices = new BLL.BaikeQuestionServices();
        IBLL.IOrderDetailServices OrderDetailServices = new BLL.OrderDetailServices();
        IBLL.IOrderServices OrderServices = new BLL.OrderServices();
        IBLL.IPostServices PostServices = new BLL.PostServices();
        IBLL.IResponseServices ResponseServices = new BLL.ResponseServices();
        IBLL.IBaikeActivityServices BaikeActivityServices = new BLL.BaikeActivityServices();
        IDBSession db = new DBSession();
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Baike() //百科
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Baike(string txttitle, string txtseries, string id_select, string txtdescribe, FormCollection fc)
        {
            var content = fc["Bcontent"];
            HttpPostedFileBase postimg = Request.Files["txtimg"];
            string filepath = postimg.FileName;
            if (filepath == "")
            {
                return Content("<script>; alert('请选择图片！'); history.go(-1) </ script >");
            }
            else
            {

                string filename = filepath.Substring(filepath.LastIndexOf("//") + 1);
                string serverpath = Server.MapPath("~/Content/Admin/Baike/img/upload/") + filename;
                string relativepath = @"~/Content/Admin/Baike/img/upload/" + filename;
                postimg.SaveAs(serverpath);
                BaikeServices.AddEntity(new Baike()
                {
                    BaikeTitle = txttitle,
                    BaikeSeries = txtseries,
                    BaikeDescribe = txtdescribe,
                    BaikeImg = relativepath,
                    BaikeType = id_select,
                    BaikeContent = content,
                    BaikeTime = DateTime.Now
                });
                db.SaveChanges();
                return View();
            }
        }
        public ActionResult UserManagement() //用户管理
        {
            var userInfo = UserInfoServices.LoadEntities(u => true).ToList();
            return View(userInfo);
        }
        public bool DeleteUser(string id)
        {
            int userid = Convert.ToInt32(id);
            var user = UserInfoServices.LoadEntities(u => u.UserId == userid).FirstOrDefault();
            var deluser = UserInfoServices.DeleteEntity(user);
            return true;
        }
        public ActionResult ShopManagement(int? page) //店铺管理
        {
            int PageSize = 6;
            int PageNumber = (page ?? 1);
            var shop = ShopServices.LoadEntities(s => true).ToList();
            return View(shop.ToPagedList(PageNumber, PageSize));
        }
        public ActionResult EditShop(int id) //店铺管理 
        {
            var shop = ShopServices.LoadEntities(s => s.ShopId == id).FirstOrDefault();
            var goods = GoodsServices.LoadEntities(g => g.ShopId == id).ToList();
            ViewBag.goods = goods.Count();
            var disgoods = GoodsServices.LoadEntities(g => g.ShopId == id && g.IsDiscount == true).ToList();
            ViewBag.disgoods = disgoods.Count();
            ViewBag.norgoods = goods.Count() - disgoods.Count();
            return View(shop);
        }
        public ActionResult EditShopGoods(int id,int ? page) //店铺商品管理 局部分页
        {
            int PageSize = 6;
            int PageNumber = (page ?? 1);
            ViewBag.id = id;
            var goods = GoodsServices.LoadEntities(g => g.ShopId == id).ToList();
            if (Request.IsAjaxRequest())
            {
                return PartialView("EditShopGoods", goods.ToPagedList(PageNumber, PageSize));
            }
            else
            {
                return View("EditShopGoods",goods.ToPagedList(PageNumber, PageSize));
            }
        }
        public ActionResult AdManagement() //百科轮播图片
        {
            var ad = BaikeActivityServices.LoadEntities(b => true).ToList();
            return View(ad);
        }
        public ActionResult EditAd(int id)//编辑
        {
            var ad = BaikeActivityServices.LoadEntities(b => b.ActivedId == id).FirstOrDefault();
            return View(ad);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditAd(string ActivedId,string ActivedTitle,string ActivedContent) //编辑
        {
            int id = Convert.ToInt32(ActivedId);
            HttpPostedFileBase postimg = Request.Files["activeimg"];
            string filepath1 = postimg.FileName;
            HttpPostedFileBase postdetail = Request.Files["activedetail"];
            string filepath2 = postdetail.FileName;
            var baike = BaikeActivityServices.LoadEntities(b => b.ActivedId == id).FirstOrDefault();
            if (filepath1 == "")
            {
                baike.ActivedImg = baike.ActivedImg;
            }
            else
            {
                string filename1 = filepath1.Substring(filepath1.LastIndexOf("//") + 1);
                string serverpath1 = Server.MapPath("~/Content/Baike/img/") + filename1;
                string relativepath1 = @"~/Content/Baike/img/" + filename1;
                postimg.SaveAs(serverpath1);
                baike.ActivedImg = relativepath1;
            }
            if (filepath2 == "")
            {
                baike.ActicedDetail = baike.ActicedDetail;
            }
            else
            {
                string filename2 = filepath2.Substring(filepath2.LastIndexOf("//") + 1);
                string serverpath2 = Server.MapPath("~/Content/Baike/img/") + filename2;
                string relativepath2 = @"~/Content/Baike/img/" + filename2;
                postimg.SaveAs(serverpath2);
                baike.ActicedDetail = relativepath2;
            }
            baike.ActivedTitle = ActivedTitle;
            baike.ActivedContent = ActivedContent;
            BaikeActivityServices.EditEntity(baike);
            db.SaveChanges();
            return Content("<script>alert('编辑成功');window.location.href='/Admin/AdManagement';</script>");
        }
        public ActionResult CreateAd()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateAd(BaikeActivity baike)
        {
            HttpPostedFileBase postimg = Request.Files["activeimg"];
            HttpPostedFileBase postdetail = Request.Files["activedetail"];
            string filepath1 = postimg.FileName;
            string filepath2 = postdetail.FileName;
            if (filepath1 == "" || filepath2 == "")
            {
                return Content("<script>;alert('图片和海报不能为空！');history.go(-1)</script >");
            }
            else
            {
                string filename1 = filepath1.Substring(filepath1.LastIndexOf("//") + 1);
                string filename2 = filepath2.Substring(filepath2.LastIndexOf("//") + 1);
                string serverpath1 = Server.MapPath("~/Content/Baike/img/") + filename1;
                string serverpath2 = Server.MapPath("~/Content/Baike/img/") + filename2;
                string relativepath1 = @"~/Content/Baike/img/" + filename1;
                string relativepath2 = @"~/Content/Baike/img/" + filename2;
                postimg.SaveAs(serverpath1);
                postdetail.SaveAs(serverpath2);
                baike.ActivedImg = relativepath1;
                baike.ActicedDetail = relativepath2;
                BaikeActivityServices.AddEntity(baike);
                return Content("<script>alert('发布成功');window.location.href='/Admin/AdManagement';</script>");
            }
          
        }
        public ActionResult DeleteAd(int id)
        {
            var ad = BaikeActivityServices.LoadEntities(b => b.ActivedId == id).FirstOrDefault();
            BaikeActivityServices.DeleteEntity(ad);
            return Content("<script>alert('删除成功');window.location.href=document.referrer;</script>");
        }
        public ActionResult BaikeManagement(int? page)
        {
            int PageSize = 8;
            int PageNumber = (page ?? 1);
            var baike = BaikeServices.LoadEntities(b => true).ToList();
            return View(baike.ToPagedList(PageNumber, PageSize));
        }
        public ActionResult DeleteBaike(int id)
        {
            var baike = BaikeServices.LoadEntities(b => b.BaikeId == id).FirstOrDefault();
            return Content("<script>alert('删除成功');window.location.href=document.referrer;</script>");
        }
        public ActionResult EditBaike(int id)
        {
            var baike = BaikeServices.LoadEntities(b => b.BaikeId == id).FirstOrDefault();
            return View(baike);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditBaike(string BaikeId, string BaikeTitle, string BaikeDescribe, FormCollection fc)
        {
            int id = Convert.ToInt32(BaikeId);
            var baike = BaikeServices.LoadEntities(b => b.BaikeId == id).FirstOrDefault();

MyPets/Controllers/TribuneController.cs
using MyPets.DALFactory;
using MyPets.IDAL;
using MyPets.Model;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyPets.Controllers
{
    public class TribuneController : Controller
    {
        IBLL.IPostServices postServices = new BLL.PostServices();
        IBLL.IResponseServices responseServices = new BLL.ResponseServices();
        IBLL.IUserInfoServices userInfoServices = new BLL.UserInfoServices();
        IDBSession db = new DBSession();
        // GET: Tribune
        public ActionResult Index(int? page)
        {
            if (Session["UserName"] != null)
            {
                var goodPostings = postServices.LoadEntities(p => p.IsChoose == true).Take(10).ToList();
                ViewData["goodPostings"] = goodPostings;
                var topPostings = postServices.LoadEntities(p => p.IsTop == true).ToList();
                ViewData["topPostings"] = topPostings;

                string userName = Session["UserName"].ToString();
                int userId = Convert.ToInt32(userInfoServices.LoadEntities(u => u.UserName == userName).FirstOrDefault().UserId);
                var postingsNum = postServices.LoadEntities(p => p.UserId == userId).ToList();
                ViewBag.postingsNum = postingsNum.Count();
                //分页控制最新发布的帖子
                int pageSize = 5;
                int pageNumber = (page ?? 1);
                var newPostings = postServices.LoadEntities(p => p.IsChoose == false && p.IsTop == false).OrderByDescending(p => p.PostTime).ToList();
                //ViewData["newPostings"] = newPostings;
                return View(newPostings.ToPagedList(pageNumber, pageSize));
            }
            else return Content("<script>alert('您还未登陆！！');history.go(-1);</script>");

        }

        public ActionResult Postings(int id, int? page)
        {

            var postFloor = responseServices.LoadEntities(r => r.PostId == id).ToList();
            ViewBag.replyNum = postFloor.Count();
            ViewBag.postId = id;
            //楼主信息
            var postTitle = postServices.LoadEntities(p => p.PostId == id).FirstOrDefault().PostTitle;
            var postContent = postServices.LoadEntities(p => p.PostId == id).FirstOrDefault().PostContent;
            var userId = postServices.LoadEntities(p => p.PostId == id).FirstOrDefault().UserId;
            var userImg = userInfoServices.LoadEntities(u => u.UserId == userId).FirstOrDefault().UserImg;
            var userName = userInfoServices.LoadEntities(u => u.UserId == userId).FirstOrDefault().UserName;

            ViewBag.postTitle = postTitle;
            ViewBag.postContent = postContent;
            ViewBag.userImg = userImg;
            ViewBag.userName = userName;

            //ViewData["postFloor"] = postFloor;
            int pageSize = 6;//每六条一页
            int pageNumber = (page ?? 1);
            return View(postFloor.ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public ActionResult Postings(string postTitle, string postType, FormCollection fc)
        {
            var content = fc["AreaDescribe"];
            if (Session["UserName"] != null)
            {
                string userName = Session["UserName"].ToString();
                var userId = userInfoServices.LoadEntities(u => u.UserName == userName).FirstOrDefault().UserId;
                var addquestion = postServices.AddEntity(new Post
                {
                    PostTitle = postTitle,
                    PostType = postType,
                    IsChoose = false,
                    IsTop = false,
                    PostContent = content,
                    PostTime = DateTime.Now,
                    UserId = userId
                });
                if (addquestion != null)
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else return Content("<script>alert('提交失败');history(-1)</script>");
            }
            else return Content("<script>alert('您还未登录呢？！');history.go(-1);</script>");
        }


        //回复帖子
        [HttpPost]
        public ActionResult ResponsePost(int id, FormCollection fc)
        {
            if (Session["UserName"] != null)//判定用户是否已登录
            {
                var postId = Convert.ToInt32(id);
                var responseContent = fc["AreaDescribe"];
                var receiverId = postServices.LoadEntities(p => p.PostId == id).FirstOrDefault().UserId;

                //设置楼层数
                var postFloor = responseServices.LoadEntities(r => r.PostId == id).ToList();
                var floorNum = postFloor.Count() + 1;

                if (responseContent != "")
                {
                    string userName = Session["UserName"].ToString();
                    var senderId = userInfoServices.LoadEntities(u => u.UserName == userName).FirstOrDefault().UserId;
                    var addRespon = responseServices.AddEntity(new Response
                    {
                        PostId = postId,
                        ResponseContent = responseContent,
                        ResponseTime = DateTime.Now,
                        SenderId = senderId,
                        ReceiverId = receiverId,
                        ResponseFloor = floorNum
                    });
                    db.SaveChanges();
                    return RedirectToAction("Postings", new { id = postId });
                }
                else return Content("<script>alert('内容不能为空！');history.go(-1);</script>");
            }
            else return Content("<script>alert('您还未登录呢？！');history.go(-1);</script>");
        }


    }
}

MyPets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MyPets/Views/Shared/_LayoutBaike.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Baike/css/style.css" rel="stylesheet" />
    <link href="~/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/bootstrap-3.3.7-dist/css/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Baike/css/bootstrap3-wysihtml5.min.css" rel="stylesheet" />
    <link href="~/Content/Baike/css/default.css" rel="stylesheet" />
    <link href="~/Content/Baike/css/SlideStyle.css" rel="stylesheet" />
    <link href="~/Content/Admin/css/StyleBar.css" rel="stylesheet" />
    @RenderSection("Add",false)
    <style type="text/css" media="screen">
        .btn.jumbo {
            font-size: 20px;
            font-weight: normal;
            padding: 14px 24px;
            margin-right: 10px;
            -webkit-border-radius: 6px;
            -moz-border-radius: 6px;
            border-radius: 6px;
        }
    </style>
</head>
<body>
    <div class="row" style="border-bottom:1px solid #a5a0a0;line-height:50px;">
        <div class="col-md-1"></div>
        <div class="col-md-1">@Html.ActionLink("宠物商城", "Index", "Home")</div>
        <div class="col-md-1">@Html.ActionLink("宠物论坛", "Index", "Tribune")</div>
        <div class="col-md-1" style="border-bottom:2px solid #9C3"><a href="javascript:;">宠物百科</a></div>
        <div class="col-md-1">@Html.ActionLink("我的店铺", "Index", "Shop")</div>
        <div class="col-md-4"></div>
        <div class="col-md-2">
            @if (Session["UserName"] == null)
            {
                <div>@Html.ActionLink("登录", "Login", "Register") | @Html.ActionLink("注册", "Register", "Register")</div>
            }
            else
            {
                <div class="dropdown">
                    <div id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <a href="javascript:;" style="color:#9C3;">@Session["UserName"]</a>
                        <span class="caret"></span>
                    </div>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="@Url.Action("Index","PersonalCenter",new { user=Session["UserName"]})">个人中心</a></li>
                        <li><a href="@Url.Action("LoginOff")">退出登录</a></li>
                    </ul>
                </div>
            }
         </div>
        <div class="col-md-1"></div>
    </div>
    <br /><br />
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-2">
            <img src="~/Content/Shop/img/logo.png" />
        </div>
        @using (Html.BeginForm("Search", "Baike", FormMethod.Post))
        {
            <div class="input-group col-md-5" style="width: 500px; margin-top: 20px; margin-right: 20%;">
                <div class="input-group">
                    <input type="text" class="form-control" name="txtBaikeTitle" placeholder="请输入文章/词条/关键字" style="border-color:#ff0000;height:46px;">
                    <span class="input-group-btn">
                        <input class="btn btn-danger btn-lg" type="submit" value="搜索">
                    </span>
                </div>
            </div>
        }
        <div class="col-md-2"></div>
    </div>
    <br />
    <div class="index_top">
        <div class="row part2">
            <div class="col-md-1"></div>
            <div class="col-md-1">@Html.ActionLink("首页", "Index")</div>
            <div class="col-md-1">@Html.ActionLink("狗狗", "ShowType", new { txttype = "狗" }) </div>
            <div class="col-md-1">@Html.ActionLink("猫咪", "ShowType", new { txttype = "猫" })</div>
            <div class="col-md-1">@Html.ActionLink("小宠", "ShowType", new { txttype = "小宠" })</div>
            <div class="col-md-1">@Html.ActionLink("水族", "ShowType", new { txttype = "水" })</div>
            <div class="col-md-1">@Html.ActionLink("问答","Answer")</div>
            <div class="col-md-5"></div>
        </div>
    </div>
    <br />
    @RenderBody()
    <script src="~/Content/Admin/js/jquery-1.11.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <script src="~/Content/Baike/js/bootstrap3-wysihtml5.all.min.js"></script>
    <script src="~/Content/Baike/js/bootstrap-wysihtml5.zh-CN.js"></script>
    <script>
        $('.textarea').wysihtml5({ locale: "zh-CN" });
    </script>
</body>
</html>

MyPets/Views/Shared/_LayoutWaterFull.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Admin/css/瀑布流/style.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="images/fav-icon.png" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }
    </script>
    <!----webfonts---->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <!-- Global CSS for the page and tiles -->
    <link href="~/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Admin/css/瀑布流/main.css" rel="stylesheet" />


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <!----start-dropdown--->
    <script type="text/javascript">
        var $ = jQuery.noConflict();
        $(function () {
            $('#activator').click(function () {
                $('#box').animate({ 'top': '0px' }, 500);
            });
            $('#boxclose').click(function () {
                $('#box').animate({ 'top': '-700px' }, 500);
            });
        });
        $(document).ready(function () {
            //Hide (Collapse) the toggle containers on load
            $(".toggle_container").hide();
            //Switch the "Open" and "Close" state per click then slide up/down (depending on open/close state)
            $(".trigger").click(function () {
                $(this).toggleClass("active").next().slideToggle("slow");
                return false; //Prevent the browser jump to the link anchor
            });

        });
    </script>
</head>
<body>
    <div class="header">
        <div class="wrap">
            <div class="logo">
                <a href="#"><img src="@Url.Content("~/Content/Shop/img/logo.png")" /></a>
            </div>
            <div class="nav-icon">
                <a href="#" class="right_bt" id="activator"><span> </span> </a>
            </div>
            <div class="box" id="box">
                <div class="box_content">
                    <div class="box_content_center">
                        <div class="form_content">
                            <div class="menu_box_list">
                                <ul>
                                    <li><a href="@Url.Action("GoodsEntry")"><span>首页</span></a></li>
                                    <li><a href="#"><span>关于</span></a></li>
                                    <li><a href="#"><span>店铺</span></a></li>
                                    <li><a href="#"><span>广告</span></a></li>
                                    <li><a href="#"><span>返回</span></a></li>
                                    <li><a href="contact.html"><span>联系</span></a></li>
                                    <li class="clear"> </li> @*<div class="clear"> </div>*@
                                </ul>
                            </div>
                            <a class="boxclose" id="boxclose"> <span> </span></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="top-searchbar">
                @using (Html.BeginForm("ShowGoods", "Admin", FormMethod.Post))
                {
                    <input type="text" name="goodstitle" />
                    <input type="submit" value="" />
                }
            </div>
            <div class="userinfo">
                <div class="user">
                    <ul>
                        <li><a href="javascript:;"><img src="@Url.Content("~/Content/Admin/images/user-pic.png")" title="user-name" /><span>管理员</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="clear"> </div>
        </div>
    </div>
    <div class="content">
        <div class="wrap">
            <div id="main" role="main">
                    @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/Content/Admin/js/jquery.imagesloaded.js"></script>
    <script src="~/Content/Admin/js/jquery.wookmark.js"></script>
    <script type="text/javascript">
        (function ($) {
            var $tiles = $('#tiles'),
                $handler = $('li', $tiles),
                $main = $('#main'),
                $window = $(window),
                $document = $(document),
                options = {
                    autoResize: true,
                    container: $main,
                    offset: 20,
                    itemWidth: 280
                };

            function applyLayout() {
                $tiles.imagesLoaded(function () {
                    // Destroy the old handler
                    if ($handler.wookmarkInstance) {
                        $handler.wookmarkInstance.clear();
                    }

                    // Create a new layout handler.
                    $handler = $('li', $tiles);
                    $handler.wookmark(options);
                });
            }

            function onScroll() {
                // Check if we're within 100 pixels of the bottom edge of the broser window.
                var winHeight = window.innerHeight ? window.innerHeight : $window.height(), // iphone fix
		            closeToBottom = ($window.scrollTop() + winHeight > $document.height() - 100);

                if (closeToBottom) {
                    // Get the first then items from the grid, clone them, and add them to the bottom of the grid
                    var $items = $('li', $tiles),
                        $firstTen = $items.slice(0, 10);
                    $tiles.append($firstTen.clone());

                    applyLayout();
                }
            };

            // Call the layout function for the first time
            applyLayout();

            // Capture scroll event.
            $window.bind('scroll.wookmark', onScroll);
        })(jQuery);
    </script>

    <div class="footer">
        <p>Copyright &copy; 2017.Company name All rights reserved.More Templates <a href="#" target="_blank" title="模板之家">宠物之家</a> - Collect from <a href="#/" title="网页模板" target="_blank">江西师大</a></p>
    </div>

</body>
</html>