MyPets/Controllers/BaikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyPets.Model;
using PagedList;
using MyPets.IDAL;
using MyPets.DALFactory;

namespace MyPets.Controllers
{
    public class BaikeController : Controller
    {
        // GET: Baike
        IBLL.IBaikeServices BaikeServices = new BLL.BaikeServices();
        IBLL.IBaikeQuestionServices BaikeQuestionServices = new BLL.BaikeQuestionServices();
        IBLL.IBaikeAnswerServices BaikeAnswerServices = new BLL.BaikeAnswerServices();
        IBLL.IResponAnswerServices ResponAnswerServices = new BLL.ResponAnswerServices();
        IBLL.IUserInfoServices UserInfoServices = new BLL.UserInfoServices();
        IBLL.IBaikeActivityServices BaikeActivityServices = new BLL.BaikeActivityServices();
        IDBSession db = new DBSession();
        public ActionResult Index()
        {
            //var s = (from b in db.Baike
            //        where b.BaikeSeries == "狗系列"
            //        select b).Skip(6).Take(6);
            var dogBaike = BaikeServices.LoadEntities(b => b.BaikeSeries == "狗系列").Take(6).ToList();
            var dogTitle = BaikeServices.LoadEntities(b => b.BaikeSeries == "狗系列").OrderBy(b => Guid.NewGuid()).Skip(6).Take(6).ToList();
            var BaikeActivity = BaikeActivityServices.LoadEntities(b => true).Take(4).ToList();
            ViewData["dog"] = dogBaike; ViewData["dogtitle"] = dogTitle;
            ViewData["active"] = BaikeActivity;
            return View();
        }
        public ActionResult Show(int id) //显示单个百科
        {
            var baike = BaikeServices.LoadEntities(b => b.BaikeId == id).FirstOrDefault();
            return View(baike);
        }
        public ActionResult GetType(string txttype, int? page) //传递百科类别分页参数
        {
            return RedirectToAction("ShowType", new { txttype, page });
        }
        public ActionResult ShowType(string txttype, int? page) //显示类别百科
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            var baike = BaikeServices.LoadEntities(b => b.BaikeType.Contains(txttype)).ToList();
            ViewBag.num = baike.Count();
            ViewData["type"] = txttype;
            return View(baike.ToPagedList(pageNumber, pageSize));

        }
        public ActionResult GetSearch(string txtBaikeTitle, int? page)
        {
            return RedirectToAction("Search", new { txtBaikeTitle, page });
        }
        public ActionResult Search(string txtBaikeTitle, int? page)//显示搜索的百科
        {
            if (txtBaikeTitle != "")
            {
                int pageSize = 5;
                int pageNumber = (page ?? 1);
                ViewBag.search = txtBaikeTitle;
                var baike = BaikeServices.LoadEntities(b => b.BaikeTitle.Contains(txtBaikeTitle)).ToList();
                ViewBag.num = baike.Count();
                ViewData["search"] = txtBaikeTitle;
                return View(baike.ToPagedList(pageNumber, pageSize));
            }
            else return Content("<script>alert('搜索不能为空！');history.go(-1);</script>");
        }
        public ActionResult ShowAd(int activeid)
        {
            var active = BaikeActivityServices.LoadEntities(b => b.ActivedId == activeid).FirstOrDefault();
            ViewBag.Title = active.ActivedTitle;
            return View(active);
        }
        public ActionResult Answer() //问答专区
        {
            return View();
        }
        public ActionResult ParticalAnswer(int? type, int? page) //局部刷新分页
        {
            int t = (type ?? 1);
            int pageSize = 9;
            int pageNumber = (page ?? 1);
            var allBaike = BaikeQuestionServices.LoadEntities(b => true).OrderByDescending(b=>b.QuestionTime).ToList();
            var goodsBaike = BaikeQuestionServices.LoadEntities(b => b.isChoiceness == true).ToList();
            switch (t)
            {
                case 1:
                    ViewBag.type = type;
                    if (Request.IsAjaxRequest())
                    {
                        return PartialView("ParticalAnswer", allBaike.ToPagedList(pageNumber, pageSize));
                    }
                    else
                    {
                        return View("ParticalAnswer", allBaike.ToPagedList(pageNumber, pageSize));
                    }
                case 2:
                    ViewBag.type = type;
                    if (Request.IsAjaxRequest())
                    {
                        return PartialView("ParticalAnswer", goodsBaike.ToPagedList(pageNumber, pageSize));
                    }
                    else
                    {
                        return View("ParticalAnswer", goodsBaike.ToPagedList(pageNumber, pageSize));
                    }
                default:
                    return View();
            }
        }
        public ActionResult SearchAnswer(string txtBaikeQuestion, int? page)
        {
            if (txtBaikeQuestion != "")
            {
                int pageSize = 6;
                int pageNumber = (page ?? 1);
                ViewBag.question = txtBaikeQuestion;
                var question = BaikeQuestionServices.LoadEntities(q => q.QuestionTitle.Contains(txtBaikeQuestion)).ToList();
                return View(question.ToPagedList(pageNumber, pageSize));
            }
            else return Content("<script>alert('请输入关键字！');history.go(-1);</script>");
        }
        public ActionResult Quiz() //提问
        {
            if (Session["UserName"] != null)
            {
                return View();
            }
            else return Content("<script>if(confirm('要登录才能提问,要去登录吗？')){ window.location.href = '/Register/Login'}else {history.go(-1);}</script>");
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Quiz(string InputTitle, string InputType, FormCollection fc) //提问
        {
            var content = fc["AreaDescribe"];
            var addquestion = BaikeQuestionServices.AddEntity(new BaikeQuestion
            {
                QuestionTitle = InputTitle,
                QuestionType = InputType,
                isChoiceness = false,
                QuestionDescribe = content,
                QuestionTime = DateTime.Now,
                UserId = 1
            });
            if (addquestion != null)
            {
                db.SaveChanges();
                return View("Answer");
            }
            else return Content("<script>alert('提交失败');history(-1)</script>");

        }
        public ActionResult ShowQuiz(int id)
        {
            //ViewModel.BaikeViewModel baikeViewModel = new ViewModel.BaikeViewModel();
            var ques = BaikeQuestionServices.LoadEntities(a => a.QuestionId == id).FirstOrDefault();
            ViewBag.head = ques.QuestionTitle; //问题标题
            ViewBag.desc = ques.QuestionDescribe; //问题描述
            ViewBag.time = ques.QuestionTime; //提问时间

            var answer = BaikeAnswerServices.LoadEntities(b => b.QuestionId == id).OrderByDescending(b => b.AnswerTime).ToList();
            ViewBag.num = answer.Count();//回答人数
            var name = UserInfoServices.LoadEntities(u => u.UserId == ques.UserId).FirstOrDefault();
            ViewBag.username = name.UserName;//提问人
            var goodsanswer = BaikeAnswerServices.LoadEntities(a => true).Take(3).OrderBy(a => Guid.NewGuid()).ToList();
            ViewData["goodsanswer"] = goodsanswer;
            Session["QuestionId"] = id;
            ViewData["answer"] = answer;
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ShowQuiz(FormCollection fc)
        {
            string name = Session["UserName"].ToString();
            var id = UserInfoServices.LoadEntities(u => u.UserName == name).FirstOrDefault();
            int userid = id.UserId;
            var answercontent = fc["AreaDescribe"];
            var addAnswer = BaikeAnswerServices.AddEntity(new BaikeAnswer
            {

                QuestionId = Convert.ToInt32(Session["QuestionId"]),
                UserId = userid,
                AnswerContent = answercontent,
                AnswerTime = DateTime.Now,
                ClickNum=0

            });
            if (addAnswer != null)
            {
                db.SaveChanges();
                return RedirectToAction("ShowQuiz", new { id = Convert.ToInt32(Session["QuestionId"]) });
            }
            else return Content("<script>;alert('提交失败！');history.go(-1)</script>");
        }
        public ActionResult LoginOff()  //退出登录
        {
            Session["UserName"] = null;
            return RedirectToAction("Index");
        }
        public ActionResult ResponAnswer(string answerid, string txtarea) 
        {
          var id = Convert.ToInt32(answerid);
          if (Session["UserName"] != null)
            {
                if (txtarea != "")
                {
                    var name = Session["UserName"].ToString();
                    var addResponAnswer = ResponAnswerServices.AddEntity(new ResponAnswer
                    {
                        AnswerId = id,
                        ResponContent = txtarea,
                        ResponTime = DateTime.Now,
                        UserName=name
                    });
                    db.SaveChanges();
                    return RedirectToAction("ShowQuiz", new { id = Convert.ToInt32(Session["QuestionId"]) });
                }
                else return Content("<script>alert('内容不能为空！');history.go(-1);</script>");
            }
            else return Content("<script>alert('您还未登录呢？！');history.go(-1);</script>");
        }
        public bool ClickGood(int id)//显示问题评论列表
        {
            var clickgood = BaikeAnswerServices.LoadEntities(b => b.AnswerId == id).FirstOrDefault();
            clickgood.ClickNum = clickgood.ClickNum + 1;
            BaikeAnswerServices.EditEntity(clickgood);
            return true;
        }
    }
}

MyPets/Controllers/TribuneController.cs
using MyPets.DALFactory;
using MyPets.IDAL;
using MyPets.Model;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyPets.Controllers
{
    public class TribuneController : Controller
    {
        IBLL.IPostServices postServices = new BLL.PostServices();
        IBLL.IResponseServices responseServices = new BLL.ResponseServices();
        IBLL.IUserInfoServices userInfoServices = new BLL.UserInfoServices();
        IDBSession db = new DBSession();
        // GET: Tribune
        public ActionResult Index(int? page)
        {
            if (Session["UserName"] != null)
            {
                var goodPostings = postServices.LoadEntities(p => p.IsChoose == true).Take(10).ToList();
                ViewData["goodPostings"] = goodPostings;
                var topPostings = postServices.LoadEntities(p => p.IsTop == true).ToList();
                ViewData["topPostings"] = topPostings;

                string userName = Session["UserName"].ToString();
                int userId = Convert.ToInt32(userInfoServices.LoadEntities(u => u.UserName == userName).FirstOrDefault().UserId);
                var postingsNum = postServices.LoadEntities(p => p.UserId == userId).ToList();
                ViewBag.postingsNum = postingsNum.Count();
                //分页控制最新发布的帖子
                int pageSize = 5;
                int pageNumber = (page ?? 1);
                var newPostings = postServices.LoadEntities(p => p.IsChoose == false && p.IsTop == false).OrderByDescending(p => p.PostTime).ToList();
                //ViewData["newPostings"] = newPostings;
                return View(newPostings.ToPagedList(pageNumber, pageSize));
            }
            else return Content("<script>alert('您还未登陆！！');history.go(-1);</script>");

        }

        public ActionResult Postings(int id, int? page)
        {

            var postFloor = responseServices.LoadEntities(r => r.PostId == id).ToList();
            ViewBag.replyNum = postFloor.Count();
            ViewBag.postId = id;
            //楼主信息
            var postTitle = postServices.LoadEntities(p => p.PostId == id).FirstOrDefault().PostTitle;
            var postContent = postServices.LoadEntities(p => p.PostId == id).FirstOrDefault().PostContent;
            var userId = postServices.LoadEntities(p => p.PostId == id).FirstOrDefault().UserId;
            var userImg = userInfoServices.LoadEntities(u => u.UserId == userId).FirstOrDefault().UserImg;
            var userName = userInfoServices.LoadEntities(u => u.UserId == userId).FirstOrDefault().UserName;

            ViewBag.postTitle = postTitle;
            ViewBag.postContent = postContent;
            ViewBag.userImg = userImg;
            ViewBag.userName = userName;

            //ViewData["postFloor"] = postFloor;
            int pageSize = 6;//每六条一页
            int pageNumber = (page ?? 1);
            return View(postFloor.ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        public ActionResult Postings(string postTitle, string postType, FormCollection fc)
        {
            var content = fc["AreaDescribe"];
            if (Session["UserName"] != null)
            {
                string userName = Session["UserName"].ToString();
                var userId = userInfoServices.LoadEntities(u => u.UserName == userName).FirstOrDefault().UserId;
                var addquestion = postServices.AddEntity(new Post
                {
                    PostTitle = postTitle,
                    PostType = postType,
                    IsChoose = false,
                    IsTop = false,
                    PostContent = content,
                    PostTime = DateTime.Now,
                    UserId = userId
                });
                if (addquestion != null)
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else return Content("<script>alert('提交失败');history(-1)</script>");
            }
            else return Content("<script>alert('您还未登录呢？！');history.go(-1);</script>");
        }


        //回复帖子
        [HttpPost]
        public ActionResult ResponsePost(int id, FormCollection fc)
        {
            if (Session["UserName"] != null)//判定用户是否已登录
            {
                var postId = Convert.ToInt32(id);
                var responseContent = fc["AreaDescribe"];
                var receiverId = postServices.LoadEntities(p => p.PostId == id).FirstOrDefault().UserId;

                //设置楼层数
                var postFloor = responseServices.LoadEntities(r => r.PostId == id).ToList();
                var floorNum = postFloor.Count() + 1;

                if (responseContent != "")
                {
                    string userName = Session["UserName"].ToString();
                    var senderId = userInfoServices.LoadEntities(u => u.UserName == userName).FirstOrDefault().UserId;
                    var addRespon = responseServices.AddEntity(new Response
                    {
                        PostId = postId,
                        ResponseContent = responseContent,
                        ResponseTime = DateTime.Now,
                        SenderId = senderId,
                        ReceiverId = receiverId,
                        ResponseFloor = floorNum
                    });
                    db.SaveChanges();
                    return RedirectToAction("Postings", new { id = postId });
                }
                else return Content("<script>alert('内容不能为空！');history.go(-1);</script>");
            }
            else return Content("<script>alert('您还未登录呢？！');history.go(-1);</script>");
        }


    }
}

MyPets/Views/Tribune/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<MyPets.Model.Post>
@*@model IEnumerable<MyPets.Model.Post>*@
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <link href="~/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Tribune/css/index.css" rel="stylesheet" />
    <script src="~/Content/Tribune/js/index.js"></script>

    @*<script src="~/ckeditor/ckeditor.js"></script>
        <script src="~/ckfinder/ckfinder.js"></script>
        <script src="~/ckfinder/config.js"></script>
        <script>
            $(function(){

                CKEDITOR.replace('AreaDescribe');
            });
        </script>*@
</head>
<body>
    <!--首页顶部-->
    <div id="index_top">
        <div class="content">
            <div class="favorite">收藏宠物之家</div>
            <ul class="index_topRight">
                @if (Session["UserName"] == null)
                {
                    <li>
                        <a href="@Url.Action("Login","Register")" id="registerState">登录</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Register", "Register")">注册</a>
                    </li>
                }
                else
                {
                    <li><a href="javascript:;" style="color:#9C3;">@Session["UserName"]</a></li>
                    <li><a href="@Url.Action("LoginOff")">退出登录</a></li>
                }
                <li>
                    <a href="">手机版</a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Baike",new { user=Session["UserName"]})">宠物百科</a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Home",new { user=Session["UserName"]})">宠物商城</a>
                </li>
            </ul>
        </div>
    </div>
    <!--首页顶部结束-->
    <!--搜索框部分-->
    <div id="search">
        <img src="~/Content/Tribune/img/logo.png" />
        <div class="search_mid">
            <input type="text" name="" id="searchTxtBox" value="" />
            <input type="button" name="searchBtn" id="searchBtn" value="搜索" />
        </div>

    </div>

    <!--搜索框部分结束-->

    <div id="TribuneContent">
        <!--左边部分-->
        <div class="LeftPart">
            <!--小指南-->
            <div class="postingsGuide">推荐资讯【置顶】</div>
            <!--小指南-->
            @foreach (MyPets.Model.Post p in ViewData["topPostings"] as List<MyPets.Model.Post>)
            {
                <div class="postingsModel">
                    <div class="postingsContent">
                        <div class="UserPhotoContent">
                            <img class="userPhoto" src="@Url.Content(p.UserInfo.UserImg)" />
                        </div>
                        <div class="belongType">【@Html.DisplayFor(t => p.PostType)】</div>
                        <div class="postingsTitle"><a href="@Url.Action("Postings","Tribune",new { id=p.PostId })">@Html.DisplayFor(t => p.PostTitle)</a></div>
                        <div class="replyNum">@p.Response.Count()</div>
                        <div class="postingsDetail">
                            <span class="postingsWriter">@Html.DisplayFor(n => p.UserInfo.UserName)</span>&nbsp;于&nbsp;<span class="postingsTime">@Html.DisplayFor(t => p.PostTime)</span>&nbsp;发表
                        </div>
                    </div>
                </div>
            }

            <!--小指南-->
            <div class="postingsGuide">最新发布</div>
            <!--小指南-->
            @foreach (@*MyPets.Model.Post p in ViewData["newPostings"] as List<MyPets.Model.Post>*@var p in Model)
            {
                <div class="postingsModel">
                    <div class="postingsContent">
                        <div class="UserPhotoContent">
                            <img class="userPhoto" src="@Url.Content(p.UserInfo.UserImg)" />
                        </div>
                        <div class="belongType">【@Html.DisplayFor(t => p.PostType)】</div>
                        <div class="postingsTitle"><a href="@Url.Action("Postings","Tribune",new { id=p.PostId })">@Html.DisplayFor(t => p.PostTitle)</a></div>
                        <div class="replyNum">@p.Response.Count()</div>
                        <div class="postingsDetail">
                            <span class="postingsWriter">@Html.DisplayFor(n => p.UserInfo.UserName)</span>&nbsp;于&nbsp;<span class="postingsTime">@Html.DisplayFor(t => p.PostTime)</span>&nbsp;发表
                        </div>
                    </div>
                </div>
            }
            <div style="margin:0 auto;width:300px;text-align:center;float:none"> @Html.PagedListPager(Model, page => Url.Action("Index", "Tribune", new { page }), new PagedListRenderOptions { LinkToFirstPageFormat = "首页", LinkToPreviousPageFormat = "上一页", LinkToNextPageFormat = "下一页", LinkToLastPageFormat = "尾页", MaximumPageNumbersToDisplay = 5 })</div>

            @*-----------------------------------------帖子模板静态--------------------------------------*@
            @*<div class="postingsModel">
                    <div class="postingsContent">
                        <div class="UserPhotoContent">
                            <img class="userPhoto" src="~/Content/Tribune/img/userPhoto.jpg" />
                        </div>
                        <div class="belongType">【求助帖】</div>
                        <div class="postingsTitle"><a href="">家里的狗狗突然不吃食了，怎么回事</a></div>
                        <div class="replyNum">7845</div>
                        <div class="postingsDetail">
                            <span class="postingsWriter">古灵精怪</span>&nbsp;于&nbsp;<span class="postingsTime">2017-5-22</span>&nbsp;发表
                        </div>
                    </div>
                </div>*@
            @*-----------------------------------------帖子模板静态--------------------------------------*@

            <!--发帖框部分-->
            @if (Session["UserName"] == null)
            {
                <p>请 <a href="@Url.Action("Login","Register")">登录</a> 发表评论</p>
            }
            else
            {
                using (Html.BeginForm("Postings", "Tribune", FormMethod.Post))
                {
                    <div id="publishPart">
                        <div class="postTitleInputBox">帖子标题：<input id="txtPostTitle" type="text" name="postTitle" /></div>
                        <div class="postTypeBox">
                            <span>选择帖子类型：</span>
                            <select id="postType" name="postType">
                                <option>交流帖</option>
                                <option>分享帖</option>
                                <option>求助帖</option>
                                <option>专家帖</option>
                            </select>
                        </div>
                        <textarea class="textarea" id="AreaDescribe" name="AreaDescribe" placeholder="输入帖子内容..."></textarea>
                        <div class="submitBox"><input type="submit" value="确认" /><a href="@Url.Action("Index")"><input type="button" value="取消" /></a></div>
                    </div>
                }
            }

            @*<script src="~/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
                <script src="~/Content/Baike/js/bootstrap3-wysihtml5.all.min.js"></script>
                <script src="~/Content/Baike/js/bootstrap-wysihtml5.zh-CN.js"></script>
                <script>
                    $('.textarea').wysihtml5({ locale: "zh-CN" });
                </script>*@

            <!--发帖框部分结束-->


        </div>
        <!--左边部分结束-->
        <!--右边部分-->
        <div class="RightPart">
            <!--个人部分-->
            @if (Session["UserName"] != null)
            {
                <div class="Personal">
                    <!--头像-->
                    <div class="PersonalPhoto">
                        <img src="~/Content/Tribune/img/userPhoto.jpg" alt="" />
                    </div>
                    <!--昵称-->
                    <div class="userName">昵称：@Session["UserName"].ToString()</div>
                    <!--等级-->
                    <div class="userLevel">等级：Lv.10</div>
                    <!--帖子数-->
                    <div class="userPostCount">发帖数：@ViewBag.postingsNum</div>
                    <!--我要发帖-->
                    <a href="#txtPostTitle"><div class="publishPost">我要发帖</div></a>
                    <!--去往个人中心-->
                    <div class="PersonalCenter"><a href="@Url.Action("Index","PersonalCenter",new { user=Session["UserName"]})">个人中心</a></div>

                </div>
            <!--个人部分结束-->
            }






            <div class="postingsType">
                <table>
                    <tr>
                        <td colspan="2" style="font-size: 14px;font-weight: 700;background: RGB(151,151,151);border-radius: 5px 5px 0 0;">帖子分类</td>
                    </tr>
                    <tr>
                        <td class="typeBlock">问题求助</td>
                        <td class="typeBlock">故事分享</td>
                    </tr>
                    <tr>
                        <td class="typeBlock">动态交流</td>
                        <td class="typeBlock">专家建议</td>
                    </tr>
                </table>
            </div>
            <div class="finePostingsContent">
                <div class="finePoTop">精华帖</div>
                @foreach (MyPets.Model.Post p in ViewData["goodPostings"] as List<MyPets.Model.Post>)
                {
                    <div class="finePositings"><a href="@Url.Action("Postings","Tribune",new { id=p.PostId })"><span class="finePoTitle">@Html.DisplayFor(t => p.PostTitle)</span></a></div>
                }
            </div>
        </div>
        <!--右边部分结束-->

        <img id="toTop" src="~/Content/Tribune/img/toTop.png" alt="" />


    </div>

</body>
</html>